# Generated by Django 6.1.1 on 2026-09-09 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('DIVORCE', 'Divorce'), ('DEATH', 'Death')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Life Event',
                'verbose_name_plural': 'Life Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_id', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('aut_reg_date', models.DateTimeField(auto_now_add=True)),
                ('family_root', models.CharField(choices=[('UMUNANGWU', 'Umunangwu'), ('UMUGBANOKE', 'Umugbanoke'), ('UMUCHUKWU', 'Umuchukwu')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number, e.g. 08012345678 or +2348012345678.', regex='^(?:0\\d{10}|\\+234\\d{10})$')])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('family_lineage', models.CharField(blank=True, max_length=200)),
                ('family_name', models.CharField(blank=True, max_length=200)),
                ('immediate_fathers_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_clan', models.CharField(blank=True, max_length=200)),
                ('mother_village', models.CharField(blank=True, max_length=200)),
                ('mother_state', models.CharField(blank=True, max_length=200)),
                ('mother_country', models.CharField(blank=True, max_length=200)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced')], max_length=20)),
                ('spouse_full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('spouse_clan', models.CharField(blank=True, max_length=200)),
                ('spouse_village', models.CharField(blank=True, max_length=200)),
                ('spouse_state', models.CharField(blank=True, max_length=200)),
                ('spouse_country', models.CharField(blank=True, max_length=200)),
                ('date_of_divorce', models.DateField(blank=True, null=True)),
                ('academic_qualification', models.CharField(blank=True, max_length=200)),
                ('area_of_profession', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Registry Record',
                'verbose_name_plural': 'Registry Records',
                'ordering': ['-aut_reg_date'],
            },
        ),
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_full_name', models.CharField(max_length=200)),
                ('date_of_marriage', models.DateField()),
                ('spouse_clan', models.CharField(blank=True, max_length=200)),
                ('spouse_village', models.CharField(blank=True, max_length=200)),
                ('spouse_state', models.CharField(blank=True, max_length=200)),
                ('spouse_country', models.CharField(blank=True, max_length=200)),
                ('life_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_details', to='registry.lifeevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='registry.registry')),
            ],
            options={
                'verbose_name': 'Marriage Detail',
                'verbose_name_plural': 'Marriage Details',
                'ordering': ['date_of_marriage'],
            },
        ),
        migrations.CreateModel(
            name='DivorceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_divorce', models.DateField()),
                ('life_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divorce_details', to='registry.lifeevent')),
                ('marriage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divorce', to='registry.marriagedetails')),
            ],
            options={
                'verbose_name': 'Divorce Detail',
                'verbose_name_plural': 'Divorce Details',
                'ordering': ['-date_of_divorce'],
            },
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='registry.registry'),
        ),
    ]
