# Generated by Django 6.1.1 on 2026-09-10 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeevent',
            name='event_type',
            field=models.CharField(choices=[('MARRIAGE', 'Marriage'), ('DIVORCE', 'Divorce'), ('DEATH', 'Death'), ('NAME_CHANGE', 'Name Change'), ('MIGRATION', 'Migration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, with an optional + at the beginning.', regex='^\\+?[0-9]+$')]),
        ),
    ]
