# Generated by Django 6.1.1 on 2026-09-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_lifeevent_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='family_lineage',
        ),
    ]
