# Generated by Django 6.1.1 on 2026-09-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_registry_family_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcedetails',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
