# Generated by Django 6.1.1 on 2026-09-27 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_divorcedetails_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameChangeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_name', models.CharField(max_length=200)),
                ('current_name', models.CharField(max_length=200)),
                ('life_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_change_details', to='registry.lifeevent')),
            ],
        ),
    ]
