# Generated by Django 6.1.1 on 2026-09-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_namechangedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='family_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registry',
            name='immediate_fathers_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registry',
            name='mother_name',
            field=models.CharField(max_length=200),
        ),
    ]
