# Generated by Django 6.1.1 on 2026-09-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_registry_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='immediate_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='registry.registry'),
        ),
    ]
