# Generated by Django 6.1.1 on 2026-09-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_registry_immediate_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='immediate_fathers_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
