# Generated by Django 6.1.1 on 2026-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_registry_immediate_fathers_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['event_type'], name='registry_li_event_t_63ed80_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeevent',
            index=models.Index(fields=['event_date'], name='registry_li_event_d_cc8bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='marriagedetails',
            index=models.Index(fields=['date_of_marriage'], name='registry_ma_date_of_423332_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['family_root'], name='registry_re_family__116cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['family_name'], name='registry_re_family__d9b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['surname'], name='registry_re_surname_d27739_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['firstname'], name='registry_re_firstna_75d1c5_idx'),
        ),
    ]
