# Generated by Django 6.1.1 on 2026-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_id', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('aut_reg_date', models.DateTimeField(auto_now_add=True)),
                ('family_root', models.CharField(choices=[('UMUNANGWU', 'Umunangwu'), ('UMUGBANOKE', 'Umugbanoke'), ('UMUCHUKWU', 'Umuchukwu')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('family_lineage', models.CharField(blank=True, max_length=200)),
                ('immediate_fathers_name', models.CharField(blank=True, max_length=200)),
                ('family_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mothers_home_town', models.CharField(blank=True, max_length=200)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced')], max_length=20)),
                ('spouse_full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('spouse_clan', models.CharField(blank=True, max_length=200)),
                ('spouse_village', models.CharField(blank=True, max_length=200)),
                ('spouse_state', models.CharField(blank=True, max_length=200)),
                ('spouse_country', models.CharField(blank=True, max_length=200)),
                ('date_of_divorce', models.DateField(blank=True, null=True)),
                ('academic_qualification', models.CharField(blank=True, max_length=200)),
                ('area_of_profession', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Registry Record',
                'verbose_name_plural': 'Registry Records',
                'ordering': ['-aut_reg_date'],
            },
        ),
    ]
