# Generated by Django 6.1.1 on 2026-09-07 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='mothers_home_town',
            new_name='mother_clan',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='note',
        ),
        migrations.AddField(
            model_name='registry',
            name='mother_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registry',
            name='mother_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registry',
            name='mother_village',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number, e.g. 08012345678 or +2348012345678.', regex='^(?:0\\d{10}|\\+234\\d{10})$')]),
        ),
    ]
