# Generated by Django 6.1.1 on 2026-09-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_rename_mothers_home_town_registry_mother_clan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('MARRIAGE', 'Marriage'), ('DIVORCE', 'Divorce'), ('DEATH', 'Death'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='registry.registry')),
            ],
            options={
                'verbose_name': 'Life Event',
                'verbose_name_plural': 'Life Events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
