# Generated by Django 6.1.1 on 2026-09-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_lifeevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifeevent',
            options={'ordering': ['-event_date'], 'verbose_name': 'Life Event', 'verbose_name_plural': 'Life Events'},
        ),
        migrations.RemoveField(
            model_name='lifeevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lifeevent',
            name='description',
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='event_type',
            field=models.CharField(choices=[('MARRIAGE', 'Marriage'), ('DIVORCE', 'Divorce'), ('DEATH', 'Death')], max_length=20),
        ),
        migrations.CreateModel(
            name='DivorceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_full_name', models.CharField(max_length=200)),
                ('date_of_marriage', models.DateField()),
                ('spouse_clan', models.CharField(blank=True, max_length=200)),
                ('spouse_village', models.CharField(blank=True, max_length=200)),
                ('spouse_state', models.CharField(blank=True, max_length=200)),
                ('spouse_country', models.CharField(blank=True, max_length=200)),
                ('date_of_divorce', models.DateField()),
                ('life_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divorce_details', to='registry.lifeevent')),
            ],
            options={
                'verbose_name': 'Divorce Detail',
                'verbose_name_plural': 'Divorce Details',
            },
        ),
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_full_name', models.CharField(max_length=200)),
                ('date_of_marriage', models.DateField()),
                ('spouse_clan', models.CharField(blank=True, max_length=200)),
                ('spouse_village', models.CharField(blank=True, max_length=200)),
                ('spouse_state', models.CharField(blank=True, max_length=200)),
                ('spouse_country', models.CharField(blank=True, max_length=200)),
                ('life_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_details', to='registry.lifeevent')),
            ],
            options={
                'verbose_name': 'Marriage Detail',
                'verbose_name_plural': 'Marriage Details',
            },
        ),
    ]
