# Generated by Django 6.1.1 on 2026-09-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_lifeevent_options_remove_lifeevent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorcedetails',
            name='date_of_marriage',
        ),
        migrations.RemoveField(
            model_name='divorcedetails',
            name='spouse_clan',
        ),
        migrations.RemoveField(
            model_name='divorcedetails',
            name='spouse_country',
        ),
        migrations.RemoveField(
            model_name='divorcedetails',
            name='spouse_state',
        ),
        migrations.RemoveField(
            model_name='divorcedetails',
            name='spouse_village',
        ),
    ]
